# Generated by Django 4.2.20 on 2025-11-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(help_text='A unique identifier for the Facebook account, e.g., username or email.', max_length=100, unique=True)),
                ('cookies', models.JSONField(help_text='The cookies required for session authentication.')),
                ('f_value', models.CharField(help_text="The 'f' value extracted from Facebook's scripts, used in some API calls.", max_length=255)),
                ('last_used', models.DateTimeField(auto_now=True, help_text='Timestamp of the last time the session was used.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
